### ISSUE TITLE
Avoid Arcade Prototype Milestone

### ISSUE THREAD

**Issue by mikewesthad** [sporadic-labs/octo-chainsaw#45]
# Concept

A mixture of [Helsing's Fire](http://www.ratloop.com/?games/helsings_fire), [Tilt to Live](http://onemanleft.com/games/tilttolive/) and a matching game.

- Single screen arcade game
- Waves of enemies spawn in endlessly
- Score is based on how long the player survives
- Player has a single active ability. It can be swapped out with alternate abilities.
- Ammo is colored light. Player can hold 1x light at a time.
- Enemies are colored and take damage when the color of the ammo matches the enemy color. 

## Today 5/21

- [x] Enemy shield
- [ ] Ability switches on pickup
- [ ] Score based on time alive
- [ ] Independent spawner for dropping ability pickups
- [ ] Abilities
  - [x] Pulse - emits from player
  - [x] Trip mine - triggered upon contact with enemy. Larger range or longer duration vs pulse.
  - [ ] Dash trail - dash and leave behind a wall of light that damages enemies
  - [x] Shield - surrounds player for a duration

## Basic Version

- [ ] Bugs
  - [ ] Navigation FPS spiking - make enemy path finding and following asynchronous and not recalculated on every frame. Enemies spawning in causes FPS spike because all path find at the same time. 
  - [ ] Screen shake bug on restart where camera remains offset
- [ ] Sound effects for enemies spawning in (potentially different sounds for different wave types)
- [ ] Enemy with shield
- [ ] Slow motion pickup
- [ ] Player shield pickup
- [ ] Enemy particles on death
- [ ] Proper UI
- [ ] Adjust player speed

## Ideas for Features

- [ ] Abilities drop as reward for killing/chaining enemies
- [ ] Pulses that trigger/destroy/mix with other pickups on the ground
- [ ] Walls that changed based on time or hitting switches
- [ ] Changing enemy movement - freeze, slow motion, pacman ghost
- [ ] Shield pickup with small radius
- [ ] Beam with reflections
- [ ] Grenade/mine
- [ ] Pickup that triggers all pulses on the ground
- [ ] Group that spawns in, targets as a group and then explodes on contact with something. E.g. arrow in tilt to live
- [ ] Pacman-style wrap around point
- [ ] Weapons/attacks (colored trap, colored shield, directed spotlight, decoy, teleport, ghost through walls)
- [ ] Allow for picking up multiple light colors and having the colors mix into one colored pulse
- [ ] Color mixing. Light in the scene that you must mix your light with to get a color that destroys certain enemies
- [ ] Difficulty curve: number of colors can increase
- [ ] Difficulty curve: number of walls in the world can increase
- [ ] Light moves at a constant speed so that it trails behind the mouse cursor
- [ ] Combo system for chaining kills
- [ ] Pickups that change the light's shape/range
- [ ] A map that scrolls infinitely horizontally - procedural levels

## Completed

- [x] Smart enemy spawning. Spawn the groups in front of the player instead of around the player.
- [x] Enemy spawn patterns (grid, tighter circle around player, random, line, sinewave)
- [x] Dashing
- [x] Screen shake on hit (or pulse). Animated tint/vignette/glitch screen on hit?
- [x] ADD SOUND!
- [x] Spawn R, G, B light pickups at Tiled locations. When player has picked up all three, spawn another set of R, G, B pickups.
- [x] Track score based on the number of light pickups collected
- [x] Shrink the player hitbox
- [x] Single screen tiled map
- [x] Light at mouse cursor (circular light with infinite range)
- [x] Enemies spawn constantly and astar to the mouse
- [x] Destroy enemies when the light color matches the enemy color
- [x] Pickup and trigger pulses at will
- [x] Optimize and switch to WebGL for shaders
